<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>03_DataDrivenTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8ddacf1e-b503-46a5-97fc-dc992e9a16da</testSuiteGuid>
   <testCaseLink>
      <guid>4afab128-b2d0-4222-8b76-cdd5696b1f84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/TC08_DataDrivenTesting_using_Excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cd22577c-fc53-4960-a851-7f325db3f5c2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/01_LoginDataForOrangeHRM_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cd22577c-fc53-4960-a851-7f325db3f5c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>959b2462-b7aa-45b3-b381-30c9d1c4b685</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd22577c-fc53-4960-a851-7f325db3f5c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>414849a7-3009-4aa4-b1db-75447ec7fdfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c695540-ef9a-4660-857a-5c7e5cb719dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Demo/TC09_DataDrivenTesting_using_CSV</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>da9555f3-5538-4a05-9c71-8b885f91c38f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/02_LoginDataForOrangeHRM_CSV</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>da9555f3-5538-4a05-9c71-8b885f91c38f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>d9a6444d-e2fb-4f69-8b03-145e9a33a45e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>da9555f3-5538-4a05-9c71-8b885f91c38f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8cbaed50-c822-41ee-b277-a24a4b14dbb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1cb9fbe-4811-4858-8ad5-81e2449c5754</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Demo/TC10_DataDrivenTesting_using_InternalData</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6a56b5a4-c6e2-405b-88d0-45d7995342ef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/03_LoginDataForOrangeHRM_InternalData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6a56b5a4-c6e2-405b-88d0-45d7995342ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>28d04b98-c8f1-498d-a83e-f558b57c0c54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a56b5a4-c6e2-405b-88d0-45d7995342ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>aba490f5-20ee-4c32-9ed2-274097d93848</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9d6b269-6daf-41f3-9a64-023de2b8cd64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Demo/TC12_DataDrivenTesting_using_Database</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f68d920-e37e-4a60-9dfd-617a14121ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>527b2f15-4012-4177-a4f4-2fe1c2a10e54</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
