<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_About 17,31,00,00,000 results (0.38 seconds)</name>
   <tag></tag>
   <elementGuidId>86bbdfc8-435a-497c-8a16-1ce6dfab1eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='result-stats']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result-stats</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aeecaa76-7fa7-4587-b062-cb8e84300546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>result-stats</value>
      <webElementGuid>ed7b8fbf-f04e-4376-8fdd-a03755bfd804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About 17,31,00,00,000 results (0.38 seconds) </value>
      <webElementGuid>864ecf9a-cd0c-4514-9376-339f3339d309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result-stats&quot;)</value>
      <webElementGuid>5e4fcf31-d53a-4395-9bdd-58b4c8088581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='result-stats']</value>
      <webElementGuid>2d22cf27-7736-487e-963f-981c10238d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slim_appbar']/div/div</value>
      <webElementGuid>763ffdea-4a5a-4121-a5f7-f7db7ea20e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verbatim'])[1]/following::div[8]</value>
      <webElementGuid>2746f537-4e4b-45df-8aff-7bd7370c2cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All results'])[2]/following::div[9]</value>
      <webElementGuid>71100a48-a93f-45f7-bce6-2b28bd463696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Settings'])[2]/preceding::div[1]</value>
      <webElementGuid>24ce06fa-1b1f-4547-8594-f67fdd9ac11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About 17,31,00,00,000 results']/parent::*</value>
      <webElementGuid>a59b243b-612b-40a0-b536-fc93e87ebd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div/div/div/div/div</value>
      <webElementGuid>a59fd18d-8073-45a9-8632-cc84e0e0168d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'result-stats' and (text() = 'About 17,31,00,00,000 results (0.38 seconds) ' or . = 'About 17,31,00,00,000 results (0.38 seconds) ')]</value>
      <webElementGuid>172bc5d4-391b-4905-abeb-04d3df867c37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
