<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Integrations</name>
   <tag></tag>
   <elementGuidId>f2ec6094-1a28-4760-bc5f-697fcf711cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > div.top_nav_item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section[2]/div/div/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26250ac3-f643-488b-a6f2-2458b5fc3a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top_nav_item</value>
      <webElementGuid>a93ed8dc-c6dc-4e9b-a8b9-25b1e9c11004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>ecf6a0c7-c01b-4185-bd81-0d71acefbb9c</value>
      <webElementGuid>0e26b77f-f95d-43b9-b926-549bb6a2199c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integrations</value>
      <webElementGuid>fbc55cf8-21a4-4251-becb-8071cbfb3700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;rebrand_header&quot;]/div[@class=&quot;wrap_container&quot;]/div[@class=&quot;left_logo_and_topnav&quot;]/div[@class=&quot;katalon_topnav&quot;]/a[1]/div[@class=&quot;top_nav_item&quot;]</value>
      <webElementGuid>53a9fe97-b5b9-43c7-a69a-a8aac9b0c556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section[2]/div/div/div/a/div</value>
      <webElementGuid>e2549660-cac0-4ea5-ad02-50cc0977ca12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Improving flaky pixel visual UI comparisons with AI methods.'])[1]/following::div[1]</value>
      <webElementGuid>70fd900a-8b80-480d-8dee-e6ecf29f9a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visual Testing'])[1]/following::div[2]</value>
      <webElementGuid>9a0edb1e-0f76-4fa5-abab-e9680dbccea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/preceding::div[2]</value>
      <webElementGuid>2d104c77-2423-4f25-9133-f384464b5f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div</value>
      <webElementGuid>3de47784-5289-47f7-95d6-84f3e1a46a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Integrations' or . = 'Integrations')]</value>
      <webElementGuid>0af109b8-643c-48c3-912e-28c9b537230a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
