<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BiDiSessionStatus</name>
   <tag></tag>
   <elementGuidId>87006eaf-c7e8-4ebb-80be-86b0929711f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'BiDiSessionStatus')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63347b45-2a42-41c7-9bf7-297858cc01ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>BiDiSessionStatus.html</value>
      <webElementGuid>6bc32ae6-be1c-4382-8c88-c61f21919725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.bidi</value>
      <webElementGuid>943e5f2c-2ced-44d9-ae2f-0bdba177387b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>31923e26-fe13-44d5-86ef-1ef0585fbb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BiDiSessionStatus</value>
      <webElementGuid>cacc87dc-ce0b-42ac-a459-35b74658e09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[2]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>747d1eb5-2d8c-49b8-912f-444ed31e0343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_org.openqa.selenium.bidi.log/iframe_packageFrame</value>
      <webElementGuid>57b69b1e-346c-4025-9a7b-c5b78bcfd9bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BiDiSessionStatus')]</value>
      <webElementGuid>7262fbe4-b7d9-49b0-aaf4-1826c46bf2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiDiProvider'])[1]/following::a[1]</value>
      <webElementGuid>35c52f86-8d8c-41b7-aa6d-06b0646aeccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiDi'])[1]/following::a[2]</value>
      <webElementGuid>c1fefc1e-e97b-4955-adba-9405819e7b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Command'])[1]/preceding::a[1]</value>
      <webElementGuid>288a325c-bae3-4902-a433-e95a36754b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connection'])[1]/preceding::a[2]</value>
      <webElementGuid>6b5b2ce0-dbea-40c3-b5c7-d63a00799db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BiDiSessionStatus']/parent::*</value>
      <webElementGuid>6f2c3dff-4f56-4f82-9171-00be56bbd580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'BiDiSessionStatus.html')]</value>
      <webElementGuid>9f5d07a9-5cc1-4c11-9fef-404764fb6211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>fd2319fe-a970-43bf-8e12-f60a5c215564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'BiDiSessionStatus.html' and @title = 'class in org.openqa.selenium.bidi' and (text() = 'BiDiSessionStatus' or . = 'BiDiSessionStatus')]</value>
      <webElementGuid>15b7c525-888a-428d-a5e8-a868913282b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
