<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium.bidi</name>
   <tag></tag>
   <elementGuidId>70c39dc4-46d5-4f8c-9bf6-5eb353f4eb4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'org.openqa.selenium.bidi')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ec04d38-2caa-4a6d-87d8-3a35b50d0597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/bidi/package-frame.html</value>
      <webElementGuid>1812f478-69de-42e2-9da4-edaed1aa9fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>e021266b-ca98-4897-854c-6ff2cb5ef2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.bidi</value>
      <webElementGuid>979e6f80-22dc-4275-9422-94f226b4c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>0be29f1a-34c5-46c6-8f15-e622138c9502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_org.openqa.selenium.bidi.log/iframe_packageListFrame</value>
      <webElementGuid>7716747a-cd3b-476c-8912-fb144db20e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium.bidi')]</value>
      <webElementGuid>596b25f7-f3a2-44c0-8667-7d67b6a2f9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium'])[1]/following::a[1]</value>
      <webElementGuid>8236bb8e-d374-4b29-9b24-bd0bc24a4c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packages'])[1]/following::a[2]</value>
      <webElementGuid>8ec62124-e178-40e9-a34b-0093cf71deff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.bidi.browsingcontext'])[1]/preceding::a[1]</value>
      <webElementGuid>e514b801-966a-47c0-97e1-f5128d49d23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.bidi.log'])[1]/preceding::a[2]</value>
      <webElementGuid>c750fd52-f8c2-4dfb-9a39-3e74761bc86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium.bidi']/parent::*</value>
      <webElementGuid>b2b93448-d65f-415b-a4be-1eac07ea7331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/bidi/package-frame.html')]</value>
      <webElementGuid>cb882d1c-cdbb-4734-895d-c1f72ddc10e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>38f3f673-0742-4b8b-a9c8-7dab49371cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/bidi/package-frame.html' and (text() = 'org.openqa.selenium.bidi' or . = 'org.openqa.selenium.bidi')]</value>
      <webElementGuid>981442a1-d84c-4118-a84a-bc6fdb27067f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
